language: java
sudo: false

# После выполнения сборки запустить скрипт для сбора статистики по JaCoCo
# Используется сторонний сервис https://codecov.io
after success:
  - bash <(curl -s https://codecov.io/bash) -t c55afc3d-3b91-4749-95c5-5c2c6d4539de

# Отправляет уведомления на почту
notifications:
  email:
    recipients:
      - murrcha@me.com
    on_success: change # default: change
    on_failure: always # default: always
