language: java
sudo: false

# После выполнения сборки запустить скрипт для сбора статистики по JaCoCo
# Используется сторонний сервис https://codecov.io
after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

services:
  - postgresql

addons:
  postgresql: "9.5"
  before_script:
    - psql -c 'create database tracker;' -U postgres

# Отправляет уведомления на почту
notifications:
  email:
    recipients:
      - murrcha@me.com
    on_success: change # default: change
    on_failure: always # default: always
